### ISSUE TITLE
why not add a features that can push a docker image to docker hub?

### ISSUE THREAD

**Issue by Edison-A-N** [common-workflow-language/cwltool#1095]
As is shown in the title, it seems that it may be helpful to use cwltool to push docker images into the docker hub rather than do it with "docker push"

**Comment by stain** [comment]
This sounds a bit out of scope for a reference implementation of a workflow engine that only is _consuming_ docker images rather than _creating_ them.

Now there is an idea (@mr-c might remind me where) of allowing ad-hoc `Dockerfile` creation (e.g. `FROM python:3 ; ADD script.py .`) but I don't think that should be extended to make cwltool a Docker creation tool.
