### ISSUE TITLE
Issue with multiple schema definitions in same file

### ISSUE THREAD

**Issue by ionox0** [common-workflow-language/cwltool#1234]
It seems that only the last type in a referenced `SchemaDef` file is able to be referenced in a workflow. With multiple type definitions, it only passes validation if only the last type definition is used. 

This may just be an issue with the `--validate` command, as the workflow seems to still run. 

## Expected Behavior
Any of the types referenced by `schema.yml#my_type` should be available in a workflow

## Actual Behavior
Only the last type that is present in the definitions file is available, and only that case successfully passes `cwltool --validate` and runs. 

## Workflow Code
schemas.yaml
```
type: record
name: my_type_one
fields:
  - name: a_field
    type: string
...
type: record
name: my_type_two
fields:
  - name: another_field
    type: string
...
```

workflow.cwl
```
...
requirements:
  SchemaDefRequirement:
    types:
      - $import: schemas.yaml
...

inputs:
  run_tools: schemas.yaml#my_type_one
...
```

```
checking object `workflows/ACCESS_pipeline.cwl#run_tools`
    Field `type` references unknown identifier `file:///Users/johnsoni/Desktop/Code/Innovation-Pipeline/resources/run_tools/schemas.yaml#my_type_one`
```

## Full Traceback
```
/usr/local/bin/cwltool 1.0.20180306140409
Resolved 'workflows/ACCESS_pipeline.cwl' to 'file:///Users/johnsoni/Desktop/Code/Innovation-Pipeline/workflows/ACCESS_pipeline.cwl'
Tool definition failed validation:
workflows/ACCESS_pipeline.cwl:26:1: checking field `inputs`
workflows/ACCESS_pipeline.cwl:28:3:   checking object `workflows/ACCESS_pipeline.cwl#run_tools`
workflows/ACCESS_pipeline.cwl:28:3:     Field `type` references unknown identifier `file:///Users/johnsoni/Desktop/Code/Innovation-Pipeline/resources/run_tools/schemas.yaml#run_tools`, tried file:///Users/johnsoni/Desktop/Code/Innovation-Pipeline/workflows/ACCESS_pipeline.cwl#file:///Users/johnsoni/Desktop/Code/Innovation-Pipeline/resources/run_tools/schemas.yaml#run_tools
```

## Your Environment
* cwltool version: 1.0.20180306140409

**Comment by mr-c** [comment]
Huh, yeah, that should work. I see that I put one definition per file the last time I personally used this feature, so I didn't experience this myself: https://github.com/EBI-Metagenomics/ebi-metagenomics-cwl/blob/master/tools/InterProScan5.21-60.cwl#L18

**Comment by mr-c** [comment]
Hmm.. maybe the issue is with your `schemas.yaml` ?

How are you separating the types? Looks like you are overwriting your map records, with multiple "type", "name" and "fields" keys.

While you can have them all in the same file, as a list of maps/dictionaries, this create difficulties when you want to import multiple type schemadefs into the same Workflow due to the limitations of `$import`. You can only import such a list like:
```
requirements:
  SchemaDefRequirement:
    types: $import: my_list_of_schemas.yml
````
Which means you can't mix together multiple lists.

So I recommend organizing your custom types as one per file like in https://github.com/EBI-Metagenomics/ebi-metagenomics-cwl/blob/master/tools/InterProScan5.21-60.cwl#L18

**Comment by ionox0** [comment]
Thank you for the info!
