### ISSUE TITLE
Coherently faking the Filesystem: PathMapper and StdFsAccess

### ISSUE THREAD

**Issue by adamnovak** [common-workflow-language/cwltool#1448]
For CWL support in Toil to work with across multiple machines, Toil needs to be able to present a coherent virtualized file system to interpreted CWL expressions and to CWL command line tools.

To do this, Toil extends the [PathMapper](https://github.com/common-workflow-language/cwltool/blob/e37134a90ac7a7c18254e30cff16da590b45c6d7/cwltool/pathmapper.py#L22), and the [StdFsAccess](https://github.com/common-workflow-language/cwltool/blob/e37134a90ac7a7c18254e30cff16da590b45c6d7/cwltool/stdfsaccess.py#L24), replacing them with a `ToilPathMapper` and a `ToilFsAccess`. However, at the moment the Toil versions don't work quite right, and I am having trouble fixing it because I'm not entirely sure what the interface I am trying to implement is.

For PathMapper, its job is to turn `location` URIs for CWL File and Directory objects into local paths (which can be anywhere on the filesystem?) and also paths in a container (which must be under a staging directory?), and also assign them a "type" depending on whether they should be writable or whether CWL is expected to create them from scratch with particular contents, and also allow mapping back from container paths to the original `location` URIs, and also allow "updating" where particular connections between URIs and files can just be inserted by something else.

Is there any documentation available for the semantics of the PathMapper methods? In particular, to implement it properly for Toil, I think I need to know:

**General PathMapper questions**
1. When the PathMapper makes a mapping, is the specified `File` or `Directory` supposed to already be visible on disk at one or both of the `resolved` and `target` paths? Does that depend on what the `type` of the path mapping ends up being?
2. Why is PathMapper reading the `dirname` field and using it for computing `target`?
3. What does the `staged` flag on a MapperEnt mean? What does `staged` mean as a `visit()` argument?
4. Is the PathMapper guaranteed to always see a recursive `listing` featuring `Directory` and `File` objects that describe the entire contents of the filesystem the workflow needs to see? Or might it sometimes see a shallow listing and be expected to map a `Directory` without access to its internal listing?

For StdFsAccess, it looks like it is used to construct the `listing` fields that the PathMapper uses, so I *think* it is meant to deal in URIs used as `location` fields on `File` and `Directory` objects, and present a coherent virtual filesystem from which `File` and `Directory` objects can be created. But it's not quite clear to me how it relates to the PathMapper: I don't see why they both exist, or how much consistency is required between them.

**PathMapper and StdFsAccess questions**
1. How if at all does the PathMapper interact with StdFsAccess?
2. Are the `fn` file paths presented to StdFsAccess coming from the namespace of PathMapper `resolved` paths (on the host), or `target` paths (on the container), or input `location` URIs (as assigned to `File` and `Directory` objects that the PathMapper starts with), or from some new, fourth namespace?
3. Is `open()` on StdFsAccess supposed to work for all URIs supported by the PathMapper, or is it an optional enhancement (it seems to lack HTTP support at the moment, which PathMapper has)?
4. If changes are made at the local paths mapped by the PathMapper, does StdFsAccess expect to see them in e.g. `listdir`?

**Comment by tetron** [comment]
> 1. When the PathMapper makes a mapping, is the specified File or Directory supposed to already be visible on disk at one or both of the resolved and target paths? Does that depend on what the type of the path mapping ends up being?

The key in the `_pathmap` dictionary is the URI that is in the `location` field.  Typically a file:// URI in cwltool but in Toil it is a FileID reference to the Toil file store.

The value in `resolved` is the file content.  For File and Directory objects it is the file path on the compute node file system that can be bind mounted into the container.  For CreateFile objects it is the actual text that will be written to create the file before the command line tool starts.

The value in `target` is where the file will be placed, from the perspective of the command line tool that's going to eventually run (e.g. the container path).

For ToilPathMapper, it calls `get_file` to resolve the FileID into a local path, which goes into "resolved".

When the starts the actual tool, it bind mounts "resolved" to "target" inside the container.

> 2. What does the staged flag on a MapperEnt mean?

If an entry in pathmap is not `staged` it is skipped by `stage_files`.  The `stage_files` method is responsible for going through the entries in a pathmap and linking/copying/moving them to their 'target' positions.  This is used to build the input directory structure for non-containerized tools, containerized tools use bind mounts.

As far as I can tell, this is mainly used to avoid recursing into directories, where we just want to link the directory and not every single file inside it.

> 3. Is the PathMapper guaranteed to always see a recursive listing featuring Directory and File objects that describe the entire contents of the filesystem the workflow needs to see? Or might it sometimes see a shallow listing and be expected to map a Directory without access to its internal listing?

The second one.  It might see a shallow listing and be expected to map a Directory without access to its internal listing -- this is correct.  This is a necessary optimization because directory listings can get very large.


> How if at all does the PathMapper interact with StdFsAccess?

It doesn't.  The pathmap is essentially a set of instructions for the `stage_files()` (without containers) or `add_volumes()` (with containers) functions that turn the pathmap into a set of actual files on disk.

> Are the fn file paths presented to StdFsAccess coming from the namespace of PathMapper resolved paths (on the host), or target paths (on the container), or input location URIs (as assigned to File and Directory objects that the PathMapper starts with), or from some new, fourth namespace?

They are in the namespace of the host where it runs, so "resolved" paths.  It accepts either plain file paths or file URIs (which are turned into local file paths).

> Is open() on StdFsAccess supposed to work for all URIs supported by the PathMapper, or is it an optional enhancement (it seems to lack HTTP support at the moment, which PathMapper has)?

It needs to support URIs or paths that can appear in "resolved".  Cwltool http support works by downloading to a local file, so then `resolved` is just the path to the local file.

> If changes are made at the local paths mapped by the PathMapper, does StdFsAccess expect to see them in e.g. listdir?

PathMapper doesn't change anything, it just creates a plan, so StdFsAccess wouldn't observe any changes until you've called a method like `stage_files()` that uses the plan to make

**Comment by adamnovak** [comment]
Thank you, this was very helpful. Understanding the PathMapper as a set of instructions makes a lot of sense.

To get the variable-depth listing generation to work right, I still need to make sure that ToilPathMapper and ToilFsAccess agree about e.g. how to enumerate the files in a virtualized directory (for the path mapper to put them somewhere real on disk when the directory is to be mapped, and for the FS access to be able to report them to cwltool when a listing is generated). But I seem to have managed it.
