### ISSUE TITLE
Pypi package installs conflicting dependencies

### ISSUE THREAD

**Issue by undu** [common-workflow-language/cwltool#253]
Steps to reproduce in arch (pip 9.0.1):
* Set up a `python2` virtual environment with `--no-site-packages`
* `pip install cwlref-runner`
* `pipconflictchecker`

Result:
```
--------------------------------------------------
 Conflicts Detected
--------------------------------------------------
 - html5lib(0.999999999) schema-salad(<=0.9999999,>=0.90)
```

Workaround:
Install html5lib before `cwlref-runner` with `pip install -I html5lib==0.9999999`, first make sure to uninstall both `cwlref-runner` and `html5lib`.

It may be related to the recent https://github.com/common-workflow-language/cwltool/commit/ab9e86e6f9c4cb25381f047a449c098c9aa4ff02

**Comment by tetron** [comment]
Thanks, I have been engaged in an ongoing battle with dependencies and this made me realize that requirements.txt may be out of sync with setup.py, which might be the problem.  I'm not familiar with `pipconflictchecker` but that looks like something we should add to the test pipeline.

**Comment by mr-c** [comment]
I believe I have fixed the root problem in schema-salad -- I've also enabled pipconflictchecker in schema-salad and cwltool and made new releases.

https://github.com/common-workflow-language/cwltool/issues/255
https://github.com/common-workflow-language/cwltool/pull/257

This issue is presumable related to #255 
@undu and @prismofeverything can verify?

**Comment by undu** [comment]
LGTM

**Comment by mr-c** [comment]
Thanks!
