### ISSUE TITLE
cwltool fails when node is not installed

### ISSUE THREAD

**Issue by StarvingMarvin** [common-workflow-language/cwltool#267]
The error I got was:

    AttributeError: 'LineCol' object has no attribute 'filename'

Which is not very descriptive. Also install instructions doesn't mention nodejs as a dependency.

**Comment by psaffrey-illumina** [comment]
I've had this error too:

https://github.com/common-workflow-language/cwltool/issues/264

I think it occurs for quite a variety of errors when the error reporting itself fails due to a lack of reference to the source file for the error. If you run cwltool with the Python debugger and break on this line, you can output the msg variable which contains something a lot more useful.

I wanted to try to put together a fix for this but I wasn't sure why the file might be going missing.

**Comment by anton-khodak** [comment]
+ for outputting `msg` variable. Would be cool if it was an explicit error message

**Comment by kapilkd13** [comment]
Hi @StarvingMarvin  Usually when I use Javascript expression with `InlineJavascriptRequirement` and node is not installed then cwltool try to create a `node` Docker Container and it works. Is this related to `InlineJsrequirement`. I think I am missing something.

**Comment by mr-c** [comment]
Looks like this was fixed in https://github.com/common-workflow-language/schema_salad/pull/85. Feel free to re-open if it happens again
