### ISSUE TITLE
Use original file/directory path as input, not one mapped under tmpdir

### ISSUE THREAD

**Issue by inutano** [common-workflow-language/cwltool#367]
Hi, I'm using cwltool to run a workflow which has a step to execute [STAR](https://github.com/alexdobin/STAR). STAR has a feature to load the reference genome index to the Linux Shared Memory to share data among different processes to reduce loading time (explained in the page 8 of https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf).

The problem is that this feature cannot be used via cwl-runner, since cwl-runner passes the input directory path mapped under tmpdir to STAR, while STAR identifies if the reference data is already loaded using the input directory path.

I understand this feature will not work with docker, but I'm wondering if there is any way to use this feature on non-docker execution. Is it possible to use the original directory path as an input, not using one mapped to the tmp?

**Comment by tetron** [comment]
Hi Tazro!

cwltool uses symbolic links to set up the tmp directory, so as a workaround you could try a wrapper script that dereferences the input to its original path (use `readlink -f`).

We could also add an option to cwltool to use original paths instead of input staging.  The reason for the current behavior is to encourage people to write portable tool wrapper by ensuring that all input files are properly accounted for.

**Comment by inutano** [comment]
Hello Peter!

Thank you for the tip, I'll give it a try. 

I agree with cwltool's current

**Comment by inutano** [comment]
I agree with cwltool's current behavior. This kind of problem should be fixed in tool configuration.. Thanks anyway!

**Comment by MatthewRalston** [comment]
I know this is an older issue... but some commandline tools (like... gzip) have issues reading through symlinks. I know this might seem out of scope, but since (de)compression support is not built into the cwl spec, nor is there a support for a `type: Link` that would supply the fully qualified path, the solution suggested here is a layer of wrapper scripts for each tool, which have to be added to the PATH and managed as additional dependencies. A recursive readlink function and/or a decompression support shouldn't be difficult to implement nor to find acceptance throught the community. I'd suggest either of the following:

- `type: Link` which returns the fully qualified path, a type which would be compatible with existing workflows
- (de)compression report for inputs/outputs, which would also be compatible going forward, and a major convenience.

**Comment by mr-c** [comment]
@MatthewRalston That is very surprising to hear about gzip! Can you share more about that?

As a workaround for now (`cwlVersion: v1.0`), you can mark those files as `writable` or use the `cwltool:InplaceUpdateRequirement` extension to force either
1) file copying if the inputs are small
2) or direct access if the inputs are large

https://github.com/common-workflow-language/cwltool/pull/317/files#diff-b6d545330a08b024b1b89b4006ad8542R11

**Comment by mr-c** [comment]
Looks like there are workarounds for gzip's behavior with respect to symlinks: https://unix.stackexchange.com/questions/137436/gzip-large-amount-of-symlinked-files

Seems like a better solution?

**Comment by MatthewRalston** [comment]
@mr-c thank you, I'll run your suggestion first thing in the morning.

Roger. I followed the advice on this thread to create a wrapper around gzip to read through the symlinks, replacing the gzip command with a reference to the wrapper `gzip.sh` below

GNU grep 3.3
cwltool 1.0.20181128175059

gzip.cwl
```yaml
baseCommand: [ gzip ] # Also tried [ gzip, -f ] as suggested on stackoverflow

inputs:
  infile:
    type: File
    inputBinding:
    position: 1
```


```bash
#!/bin/bash
gzip $(readlink -f $1)
```
I can upload my rnaseq workflow if necessary to completely reproduce the issue, but I believe the above reproduces the issue. The fastq files are coming directly from a [trimmomatic step](https://github.com/common-workflow-language/workflows/blob/master/tools/trimmomatic.cwl) in CommonWorkflowLanguage/workflows that produces uncompressed fastqs. I have a subworkflow that takes gzip'd fastqs as input and runs fine alone. Before the subworkflow I recompress the trimmed files and this is the step that is failing, downstream of trimmomatic and upstream of the subworkflow. The gzip command is throwing the symlink error, but it highlights the utility of compression features.

**Comment by mr-c** [comment]
The following works for me, using `cwltool` with and without a container:

``` cwl
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: CommandLineTool

baseCommand: [ gzip, -c ] 

inputs:
  file:
    type: File
    inputBinding:
      position: 1

stdout: $(inputs.file.basename).gz

outputs:
  gz_file:
    type: File
    outputBinding:
      glob: $(inputs.file.basename).gz
```

**Comment by tetron** [comment]
@MatthewRalston The issue is that the default behavior of gzip is to replace the original file with the compressed one, but destructively modifying inputs that way is illegal in CWL.  See @mr-c's note about either using `writable` or `gzip -c` to create a separate compressed file.
