### ISSUE TITLE
removal of warning due to updatable inputs feature

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#382]
```
unrecognized extension field `http://commonwl.org/cwltool#generation`.  Did you include a $schemas section?
```
Very cool feature, but no need to print this warning

Presumably related to https://github.com/common-workflow-language/cwltool/pull/317

**Comment by kapilkd13** [comment]
Hi @mr-c  I am looking at this issue. This arises because here https://github.com/common-workflow-language/cwltool/blob/master/cwltool/draft2tool.py#L540 we are setting generation in the datum, and later validating the schema in line [547](https://github.com/common-workflow-language/cwltool/blob/master/cwltool/draft2tool.py#L547) In validation step this `generation` field is checked if it is present in `expected_scheme` [here](https://github.com/common-workflow-language/schema_salad/blob/master/schema_salad/validate.py#L293) and as it is not present in scheme it throws this warning.
I can think of two ways to solve this:
1. somehow add the `generation` field to the `expected_scheme`, so that it goes for validation and passes.
2. Add generation field to datum after validation is done so that this field never go for validation.
I tested second method and its working fine. Should we go with second method?

**Comment by mr-c** [comment]
Let's try number 2, also we should filter it out of the output object

**Comment by kapilkd13** [comment]
@mr-c  do you mean it should not be present in output like here
```
[jolb rev] completed success
[joyb rev] {
    "output": {
        "checksum": "sha1$97fe1b50b4582cebc7d853796ebd62e3e163aa3f", 
        "basename": "output.txt", 
        "nameext": ".txt", 
        "nameroot": "output", 
        "http://commonwl.org/cwltool#generation": 0, 
        "location": "file:///C:/users/kapilk%7E1/appdata/local/temp/tmpygovsh/output.txt", 
        "class": "File", 
        "size": 1111
    }
}
```
I asked this because the reason we are having this warning is that we are adding `generation` field while collecting output. In this case solution would simply be to avoid setting generation by removing these 2 lines here https://github.com/common-workflow-language/cwltool/blob/master/cwltool/draft2tool.py#L540 
Should we do this.

**Comment by mr-c** [comment]
It should be removed from the final output object, the intermediate ones are fine for now.
