### ISSUE TITLE
--cachedir needs to take `stdout` field into account when calculating the hash

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#408]

**Comment by kapilkd13** [comment]
Hi @mr-c, here does `stdout` field means whatever is written to stdout should be used in calculating cache hash. We are calculating cache key here https://github.com/common-workflow-language/cwltool/blob/master/cwltool/draft2tool.py#L298 I mean from where can we obtain `stdout` field inside this function.
Also I personally feel that instead of calculating `keydict` of values that go inside cachekey calculation in `Job` function, we can pass it as a argument, starting from main function and propagating to all intermediate function adding value to it whenever necessary and finally resolving inside `job` function. This can allow us to avoid `parameter references` that may come inside our prepared cmdline https://github.com/common-workflow-language/cwltool/blob/master/cwltool/draft2tool.py#L274 
Is this possible?

**Comment by mr-c** [comment]
Here are the ingredients for this issue
1) `type: stdout` without and accompanying `stdout: my_stdout_name` results in a randomly named file that `stdout` is redirected to. This isn't very reproducible! Suggested fix: make the generation of this name stable as long as the tool nor its inputs change
2) As you point out, the cache key calculation doesn't take the name of the stdout field into effect. This also need to be fixed

**Comment by mr-c** [comment]
for 1. see https://github.com/common-workflow-language/cwltool/blob/master/cwltool/load_tool.py#L91

**Comment by mr-c** [comment]
for 2. Change https://github.com/common-workflow-language/cwltool/blob/master/cwltool/draft2tool.py#L274 to be `keydict = {u"cmdline": cmdline, u"stdout",  ... }`
