### ISSUE TITLE
support parallel thread execution

### ISSUE THREAD

**Issue by itajaja** [common-workflow-language/cwltool#565]
It would be nice to support parallel thread execution, and I would be happy to contribute to that. How big of an effort do you guys think this would be? Suggestions welcome :)

**Comment by tetron** [comment]
Not actually that bad.  The core engine is already capable, it just needs a multiprocess executor to manage processes.

I guess we don't have a ticket for this already.

Here's the gist of it.  `jobiter` is a generator object which, when iterated over, produces either `Job` objects or `None`.  Each job object has a `run()` method.

```
def single_job_executor(t,  # type: Process
                        job_order_object,  # type: Dict[Text, Any]
                        **kwargs  # type: Any
                        ):
...
    jobiter = t.job(job_order_object,
                    output_callback,
                    **kwargs)
    try:
        for r in jobiter:
            if r:
                builder = kwargs.get("builder", None)  # type: Builder
                if builder is not None:
                    r.builder = builder
                if r.outdir:
                    output_dirs.add(r.outdir)
                r.run(**kwargs)
            else:
                _logger.error("Workflow cannot make any more progress.")
                break
    except WorkflowException:
        raise
    except Exception as e:
        _logger.exception("Got workflow error")
        raise WorkflowException(Text(e))
```

In order to make a multiprocess executor, you need to:

1. Add a workflow execution lock
2. Take the workflow execution lock when calling `jobiter`
3. Call the run() method in a thread so it doesn't block the main loop
4. Keep a table of running processes
4. Inside run(), after the process completes, take the workflow execution lock, call the output callback, and update the running process table
5. If `jobiter` returns None, check the running process table.  If there are running processes, sleep a bit and try again.  If there are no running processes, the workflow is deadlocked and fails.
