### ISSUE TITLE
cwltool --validate very verbose with schemas

### ISSUE THREAD

**Issue by keiranmraine** [common-workflow-language/cwltool#678]
## Expected Behavior

Less noisy output when validating cwl files, `--quiet` doesn't change output of `foreign properties`

## Actual Behavior

When loading a cwl with schemas sections I'm seeing a line being generated of ~30k characters:

```
foreign properties {'http:/..........}
```

## Workflow Code
Not sure relevant but [here](https://github.com/cancerit/dockstore-cgpmap/blob/639ef8a22e7030ed61929884aafef930cf641910/Dockstore.cwl).

## Full Traceback
Link to [relevant lines of travis](https://travis-ci.org/cancerit/dockstore-cgpmap/jobs/346729253#L2747-L2754) output.

## Your Environment
* cwltool version: 1.0.20180224135035

**Comment by mr-c** [comment]
Hello @keiranmraine and thank you for your issue.

I agree that we could explain this better.

The issue is that you use `dct` but it is missing from your [`$namespace`](https://github.com/cancerit/dockstore-cgpmap/blob/639ef8a22e7030ed61929884aafef930cf641910/Dockstore.cwl#L131) section

Seems redundant with your [`s:author`](https://github.com/cancerit/dockstore-cgpmap/blob/639ef8a22e7030ed61929884aafef930cf641910/Dockstore.cwl#L136) section, so maybe remove the `dct:creator`?

**Comment by keiranmraine** [comment]
Ah yes, I've confirmed that I can safely remove `dct`with the next release of Dockstore and doing so removes the verbosity issue.

Thanks
