### ISSUE TITLE
--update no longer exists

### ISSUE THREAD

**Issue by jpatricia** [common-workflow-language/cwltool#87]
Hi,
We noticed that the `--update` option was deleted in this commit.
https://github.com/common-workflow-language/cwltool/commit/f0211266e8536a54adc61a7fac88bbcadf449b6c#diff-7e9ba38c5e8dd21caad9558b5d833a79L119

Was this intentional? It looks like the supporting code in `cwltool/update.py` was not actually deleted.
Thanks!

**Comment by tetron** [comment]
Hi @jpatricia sorry about that, I took that out as part of a bigger refactor of tool loading and should have put it back.  I need to tweak the feature slightly so that it updates to a specified version instead of the "latest" version (which in the case of cwltool is draft-4.dev1 internally which shouldn't be used except for draft development).

**Comment by mr-c** [comment]
Hello @jpatricia , `--update` has been replaced by the new `cwl-upgrader` tool for upgrading `draft-3` to `v1.0` CWL documents

https://github.com/common-workflow-language/cwl-upgrader/

Please let us know via https://github.com/common-workflow-language/cwl-upgrader/issues if you have any problems!
